// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw12_ef.Models;

#nullable disable

namespace cw12_ef.Migrations
{
    [DbContext(typeof(GamesContext))]
    [Migration("20250922134837_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("cw12_ef.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 59.990000000000002,
                            Publisher = "Nintendo",
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            Price = 49.990000000000002,
                            Publisher = "CD Projekt Red",
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 3,
                            Price = 59.990000000000002,
                            Publisher = "Bandai Namco Entertainment",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 4,
                            Price = 4.9900000000000002,
                            Publisher = "Innersloth",
                            Title = "Among Us"
                        },
                        new
                        {
                            Id = 5,
                            Price = 14.99,
                            Publisher = "Team Cherry",
                            Title = "Hollow Knight"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
